name: pytorch_ros
channels:
  - pytorch3d
  - iopath
  - fvcore
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - blosc=1.21.0=h8c45485_0
  - brotli=1.0.9=he6710b0_2
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.5.18.1=ha878542_0
  - cached-property=1.5.2=py_0
  - certifi=2022.6.15=py38h06a4308_0
  - cfitsio=3.470=hf0d0db6_6
  - charls=2.2.0=h2531618_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2022.5.0=py38h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - fsspec=2022.3.0=py38h06a4308_0
  - fvcore=0.1.5.post20210915=py38
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - h5py=3.2.1=py38h6c542dc_0
  - hdf5=1.10.6=hb1b8bf9_0
  - imagecodecs=2021.8.26=py38h4cda21f_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=py38
  - jpeg=9d=h7f8727e_0
  - jxrlib=1.1=h7b6447c_2
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libcurl=7.82.0=h0b77cf5_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libzopfli=1.0.3=he6710b0_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h7f8727e_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.7.1=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1o=h7f8727e_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pillow=8.4.0=py38h5aabda8_0
  - pip=21.2.4=py38h06a4308_0
  - portalocker=2.4.0=py38h578d9bd_0
  - python=3.8.12=h12debd9_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.6.2=py38_cu113_pyt1100
  - pywavelets=1.3.0=py38h7f8727e_0
  - readline=8.1=h27cfd23_0
  - scikit-image=0.19.2=py38h51133e4_0
  - scipy=1.7.3=py38hc147768_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.9=h295c915_0
  - sqlite=3.36.0=hc218d9a_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - termcolor=1.1.0=py_2
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.11=h1ccaba5_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.10.0=py38_cu113
  - torchvision=0.11.1=py38_cu113
  - tqdm=4.64.0=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7b6447c_0
  - zfp=0.5.5=h295c915_6
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.1.0
    - ansitable==0.9.6
    - anyio==3.3.4
    - argon2-cffi==21.1.0
    - attrdict==2.0.1
    - attrs==21.2.0
    - av==9.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.1.0
    - cachetools==5.2.0
    - catkin-pkg==0.5.2
    - cffi==1.15.0
    - charset-normalizer==2.0.7
    - colored==1.4.3
    - debugpy==1.5.1
    - decorator==5.1.0
    - defusedxml==0.7.1
    - distro==1.8.0
    - docutils==0.19
    - entrypoints==0.3
    - gnupg==2.3.1
    - google-auth==2.8.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - idna==3.3
    - imageio==2.10.1
    - importlib-metadata==4.11.4
    - imutils==0.5.4
    - ipykernel==6.5.0
    - ipython==7.29.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.2
    - json5==0.9.6
    - jsonschema==4.1.2
    - jupyter-client==7.0.6
    - jupyter-core==4.9.1
    - jupyter-server==1.11.2
    - jupyterlab==3.2.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.2
    - kornia==0.6.3
    - markdown==3.3.7
    - markupsafe==2.0.1
    - matlabengineforpython==R2021a
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - nbclassic==0.3.4
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.5
    - numpy==1.22.4
    - oauthlib==3.2.0
    - opencv-contrib-python==4.5.4.58
    - packaging==21.2
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pgraph-python==0.6.1
    - pickleshare==0.7.5
    - progress==1.6
    - progressbar==2.5
    - prometheus-client==0.12.0
    - prompt-toolkit==3.0.21
    - protobuf==3.19.4
    - psutil==5.9.3
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pycryptodomex==3.15.0
    - pygments==2.10.0
    - pymunk==6.2.1
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pyyaml==6.0
    - pyzmq==22.3.0
    - requests==2.26.0
    - requests-oauthlib==1.3.1
    - roboticstoolbox-python==1.0.1
    - rospkg==1.4.0
    - rsa==4.8
    - rtb-data==1.0.0
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - scikit-fmm==2022.3.26
    - send2trash==1.8.0
    - sniffio==1.2.0
    - spatialgeometry==1.0.1
    - spatialmath-python==1.0.0
    - swift-sim==1.0.0
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.12.1
    - testpath==0.5.0
    - tornado==6.1
    - traitlets==5.1.1
    - transforms3d==0.3.1
    - urllib3==1.26.7
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - websockets==10.3
    - werkzeug==2.1.2
    - zipp==3.8.0
prefix: /home/jingpei/anaconda3/envs/pytorch_ros
